name: xwidget
description: A package for building dynamic UIs in Flutter using an expressive, XML based markup language.
version: 0.4.1
repository: https://github.com/appfluent/xwidget
issue_tracker: https://github.com/appfluent/xwidget/issues

topics:
  - dynamic-ui
  - server-driven-ui
  - xml
  - widgets
  - analytics

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.9
  crypto: ^3.0.7
  http: ^1.6.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  xml: ^6.6.1
  web: ^1.1.1
  xwidget_el: ^0.4.0

dev_dependencies:
  args: ^2.7.0
  flutter_test:
    sdk: flutter
  lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# The following section is specific to Flutter packages.
flutter:
