# XWidget default config

# inflater options
inflaters:
  target: "lib/xwidget/generated/inflaters.g.dart"

  imports: [
    "package:xwidget/xwidget.dart",
  ]

  sources: [ ]

  includes: [ ]

  constructor_exclusions: [
    "CachedNetworkImage:imageRenderMethodForWeb",
  ]

  # TODO: find a way to read variable object defaults from source
  # Unfortunately, the analyzer's public API is very limiting. The information is there, but
  # we can't access it unless they make it public. For now we'll just have to maintain this map.
  constructor_arg_defaults:
    "AnimatedCrossFade:layoutBuilder": "AnimatedCrossFade.defaultLayoutBuilder"
    "BoxShadow:color": "const Color(0xFF000000)"
    "CupertinoSliverRefreshControl:builder": "CupertinoSliverRefreshControl.buildRefreshIndicator"
    "CupertinoTextField:placeholderStyle": "const TextStyle(fontWeight: FontWeight.w400, color: CupertinoColors.placeholderText)"
    "CupertinoTextField.borderless:placeholderStyle": "const TextStyle(fontWeight: FontWeight.w400, color: CupertinoColors.placeholderText)"
    "Dialog:insetPadding": "const EdgeInsets.symmetric(horizontal: 40.0, vertical: 24.0)"
    "FloatingActionButton:heroTag": "'<default FloatingActionButton hero tag>'"
    "FloatingActionButton.small:heroTag": "'<default FloatingActionButton hero tag>'"
    "FloatingActionButton.large:heroTag": "'<default FloatingActionButton hero tag>'"
    "FloatingActionButton.extended:heroTag": "'<default FloatingActionButton hero tag>'"
    "Scaffold:bottomSheetScrimBuilder" : "defaultBottomSheetScrimBuilder"
    "SlidableAction:backgroundColor": "Colors.white"
    "Text:data": "XWidgetUtils.joinStrings(text)"
    "WidgetSpan:alignment": "PlaceholderAlignment.middle"
    "*:colorBlendMode": "BlendMode.srcIn"
    "*:selectionHeightStyle": "BoxHeightStyle.tight"
    "*:selectionWidthStyle": "BoxWidthStyle.tight"

  constructor_arg_parsers:
    # basic types
    "bool": "parseBool(value)"
    "double": "parseDouble(value)"
    "int": "parseInt(value)"
    "String": "value"

    # complex types
    "Alignment": "parseAlignment(value)"
    "AlignmentDirectional": "parseAlignmentDirectional(value)"
    "AlignmentGeometry": "parseAlignmentGeometry(value)"
    "Duration": "parseDuration(value)"
    "BorderRadius": "parseBorderRadius(value)"
    "BorderRadiusGeometry": "parseBorderRadius(value)"
    "Color": "parseColor(value)"
    "Curve": "parseCurve(value)"
    "EdgeInsets": "parseEdgeInsets(value)"
    "EdgeInsetsGeometry": "parseEdgeInsetsGeometry(value)"
    "IconData": "parseIcon(value)"
    "InputBorder": "parseInputBorder(value)"
    "FontWeight": "parseFontWeight(value)"
    "Key": "parseKey(value)"
    "List<String>": "parseListOfStrings(value)"
    "List<double>": "parseListOfDoubles(value)"
    "List<int>": "parseListOfInts(value)"
    "Locale": "parseLocale(value)"
    "MaterialStateProperty<Color>": "parseMaterialStateColor(value)"
    "MaterialStateProperty<double>": "parseMaterialStateDouble(value)"
    "MaterialStateProperty<EdgeInsetsGeometry>": "parseMaterialStateEdgeInsets(value)"
    "MaterialStateProperty<Size>": "parseMaterialStateSize(value)"
    "Offset": "parseOffset(value)"
    "Size": "parseSize(value)"
    "TextDecoration": "parseTextDecoration(value)"
    "TextInputType": "parseTextInputType(value)"
    "VisualDensity": "parseVisualDensity(value)"
    "WidgetStateProperty<Color>": "parseWidgetStateColor(value)"
    "WidgetStateProperty<double>": "parseWidgetStateDouble(value)"
    "WidgetStateProperty<EdgeInsetsGeometry>": "parseWidgetStateEdgeInsets(value)"
    "WidgetStateProperty<Size>": "parseWidgetStateSize(value)"

    # type/class agnostic - for specific attributes
    "*:width": "parseDouble(value)"
    "*:height": "parseDouble(value)"
    "*:icon": "parseIcon(value)"
    "*:activeIcon": "parseIcon(value)"

schema:
  target: "xwidget_schema.g.xsd"
  template: "xwidget|res/schema_template.xsd"

  types:
    "bool": "boolAttributeType"
    "Alignment": "AlignmentAttributeType"
    "AlignmentDirectional": "AlignmentDirectionalAttributeType"
    "AlignmentGeometry": "AlignmentGeometryAttributeType"
    "Curve": "CurvesAttributeType"
    "FontWeight": "FontWeightAttributeType"
    "InputBorder": "InputBorderAttributeType"
    "TextDecoration": "TextDecorationAttributeType"
    "TextInputType": "TextInputTypeAttributeType"

  attribute_exclusions: [
    "*:child",
  ]

# controller options
controllers:
  target: "lib/xwidget/generated/controllers.g.dart"

  imports: [
    "package:xwidget/xwidget.dart",
  ]

  sources: [
    "lib/xwidget/controllers/**.dart"
  ]

# icon options
icons:
  target: "lib/xwidget/generated/icons.g.dart"

  imports: [
    "package:xwidget/xwidget.dart",
  ]

  sources: [ ]
